import cn from 'classnames';
import { useStore } from 'effector-react';
import Head from 'next/head';
import Link from 'next/link';
import { getUrl, NavLink, useContext, userRolesToIcons } from '../lib/utils';
import s from './Layout.module.css';

const Layout = ({ children }: any) => {
  const { $session, actions } = useContext();
  const { currentUser, isSignedIn } = useStore($session);
  const userIconClass = role => cn(s.userRoleIcon, 'mr-1', userRolesToIcons[role]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={s.header}>
          <div className={cn('container', s.headerFg)}>
            <div className="flex items-center">
              <img src="/img/storm.svg" className={cn('mr-7', s.logo)} />
              <div className="flex">
                <NavLink href={getUrl('home')}>Home</NavLink>
                <NavLink href={getUrl('users')}>Users</NavLink>
                <NavLink href={getUrl('articles')}>Articles</NavLink>
                <NavLink href={getUrl('tags')}>Tags</NavLink>
              </div>
            </div>
            {isSignedIn ? (
              <div className="flex items-center">
                <i className={userIconClass(currentUser.role)}></i>
                <div className={cn('mr-2', s.userName)}>{currentUser.name}</div>
                <i
                  className={cn('fa fa-sign-out-alt', s.signIcon)}
                  title="Sign out"
                  onClick={() => actions.signOut()}
                ></i>
              </div>
            ) : (
              <Link href={getUrl('newSession')} className={s.signIn}>
                <div className={s.signInText}>Sign In</div>
                <i className={cn('fa fa-sign-in-alt', s.signIcon)} title="Sign in"></i>
              </Link>
            )}
          </div>
        </div>
        <div className={cn('container', s.content)}>{children}</div>
      </div>
      <div id="tooltipRoot"></div>
    </>
  );
};

export default Layout;
